# Setup
title:               'Madan Y N'
tagline:             'At the crossroads of chaos and clarity'
description:         'Skywalker'
url:                 http://madanyn3.github.io
baseurl:             /
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              'Madan Y N'
  url:               https://github.com/madanyn3/
  email:             madanyn3@gmail.com

# Gems
plugins:
  - jekyll-paginate

# Collections
collections:
  blogs:
    output: true
    permalink: /blogs/:title/

# Custom vars
version:             3.14
google_analytics_id: #UA-XXXX-Y
